/**
 * Query Types
 */

export interface QueryOptions {
  limit?: number;
  offset?: number;
}

export interface SemanticSearchOptions {
  topK?: number;
  vectorIndex?: string;
  threshold?: number;
  minScore?: number;
  /**
   * Override or enrich operation metadata
   * @param results - Results after this operation
   * @param metadata - Default metadata generated by the operation
   * @returns Modified metadata
   */
  metadataOverride?: (results: any[], metadata: any) => any;
}

export interface ExpandOptions {
  depth?: number;
  direction?: 'outgoing' | 'incoming' | 'both';
}

export interface FilterOperators<T> {
  equals?: T;
  contains?: T extends string ? string : never;
  startsWith?: T extends string ? string : never;
  endsWith?: T extends string ? string : never;
  gt?: T extends number ? number : never;
  gte?: T extends number ? number : never;
  lt?: T extends number ? number : never;
  lte?: T extends number ? number : never;
  in?: T[];
}

export type FilterValue<T> = T | FilterOperators<T>;

export interface QueryPlan {
  cypher: string;
  params: Record<string, any>;
  estimatedRows?: number;
  indexesUsed?: string[];
  executionSteps?: string[];
}

export interface CypherQuery {
  query: string;
  params: Record<string, any>;
}
